import express from 'express'; import cors from 'cors'; import path from 'path'; import fs from 'fs';
import { PrismaClient } from '@prisma/client'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import multer from 'multer';
const prisma=new PrismaClient(); const app=express(); const port=Number(process.env.PORT||4000); const secret=process.env.JWT_SECRET||'dev-secret';
app.use(cors()); app.use(express.json({limit:'10mb'}));
const uploadDir=process.env.UPLOAD_DIR||path.join(process.cwd(),'uploads'); fs.mkdirSync(uploadDir,{recursive:true});
app.use('/uploads',express.static(uploadDir));
const upload=multer({dest:uploadDir,limits:{fileSize:15*1024*1024}});
function token(user:any){return jwt.sign({id:user.id,role:user.role},secret,{expiresIn:'7d'});} 
function auth(req:any,res:any,next:any){try{const h=req.headers.authorization||''; req.user=jwt.verify(h.replace('Bearer ',''),secret); next()}catch{return res.status(401).json({error:'Unauthorized'})}}
app.get('/api/health',(_,res)=>res.json({ok:true,app:'Gunashree Digital'}));
app.post('/api/auth/register',async(req,res)=>{try{const {name,phone,password,email}=req.body; if(!name||!phone||!password)return res.status(400).json({error:'name, phone and password required'}); const exists=await prisma.user.findUnique({where:{phone}}); if(exists)return res.status(409).json({error:'Phone already registered'}); const user=await prisma.user.create({data:{name,phone,email,passwordHash:await bcrypt.hash(password,10)}}); res.json({token:token(user),user:{id:user.id,name:user.name,phone:user.phone,role:user.role}})}catch(e){res.status(500).json({error:'Registration failed'})}});
app.post('/api/auth/login',async(req,res)=>{const {phone,password}=req.body; const user=await prisma.user.findUnique({where:{phone}}); if(!user?.passwordHash||!(await bcrypt.compare(password,user.passwordHash)))return res.status(401).json({error:'Invalid credentials'}); res.json({token:token(user),user:{id:user.id,name:user.name,phone:user.phone,role:user.role}})});
app.get('/api/categories',async(_,res)=>res.json(await prisma.category.findMany({include:{_count:{select:{templates:true}}},orderBy:{name:'asc'}})));
app.post('/api/categories',auth,async(req,res)=>{if(req.user.role!=='ADMIN')return res.sendStatus(403); res.json(await prisma.category.create({data:{name:req.body.name,slug:req.body.slug||req.body.name.toLowerCase().replace(/\s+/g,'-')}}))});
app.get('/api/templates',async(req,res)=>{const requested=(req.query.status as string)||'PUBLISHED'; const where=requested==='ALL'?{}:{status:requested}; res.json(await prisma.template.findMany({where,include:{category:true},orderBy:{updatedAt:'desc'}}))});
app.post('/api/templates',auth,async(req,res)=>{if(req.user.role!=='ADMIN')return res.sendStatus(403); const b=req.body; const schema={version:1,fields:Array.isArray(b.fields)?b.fields:['NAME','BUSINESS_NAME','MOBILE','ADDRESS','PHOTO','LOGO'],...(b.schema||{})}; const t=await prisma.template.create({data:{title:b.title,slug:b.slug,thumbnailUrl:b.thumbnailUrl,backgroundUrl:b.backgroundUrl,width:b.width||1080,height:b.height||1350,status:b.status||'DRAFT',categoryId:b.categoryId||null,schema}}); res.json(t)});
app.patch('/api/templates/:id',auth,async(req,res)=>{if(req.user.role!=='ADMIN')return res.sendStatus(403); res.json(await prisma.template.update({where:{id:req.params.id},data:req.body}))});
app.delete('/api/templates/:id',auth,async(req,res)=>{if(req.user.role!=='ADMIN')return res.sendStatus(403); await prisma.template.delete({where:{id:req.params.id}}); res.sendStatus(204)});
app.post('/api/media',auth,upload.single('file'),async(req,res)=>{if(req.user.role!=='ADMIN')return res.sendStatus(403); if(!req.file)return res.status(400).json({error:'file required'}); const url=`/uploads/${req.file.filename}`; res.json(await prisma.media.create({data:{filename:req.file.originalname,url,mimeType:req.file.mimetype,size:req.file.size}}))});
app.get('/api/media',auth,async(_,res)=>res.json(await prisma.media.findMany({orderBy:{createdAt:'desc'}})));
app.post('/api/designs',auth,async(req,res)=>{const d=await prisma.design.create({data:{name:req.body.name||'Untitled Design',data:req.body.data||{},templateId:req.body.templateId||null,userId:req.user.id}}); res.json(d)});
app.get('/api/designs',auth,async(req,res)=>{const where=req.user.role==='ADMIN'&&req.query.all?{}:{userId:req.user.id}; res.json(await prisma.design.findMany({where,include:{template:true,user:{select:{name:true,phone:true}}},orderBy:{updatedAt:'desc'}}))});
app.patch('/api/designs/:id',auth,async(req,res)=>{const d=await prisma.design.findUnique({where:{id:req.params.id}}); if(!d||(req.user.role!=='ADMIN'&&d.userId!==req.user.id))return res.sendStatus(403); res.json(await prisma.design.update({where:{id:d.id},data:{name:req.body.name,data:req.body.data,outputUrl:req.body.outputUrl}}))});
app.get('/api/admin/stats',auth,async(req,res)=>{if(req.user.role!=='ADMIN')return res.sendStatus(403); const [users,templates,designs,media]=await Promise.all([prisma.user.count(),prisma.template.count(),prisma.design.count(),prisma.media.count()]); res.json({users,templates,designs,media})});
app.listen(port,()=>console.log(`Gunashree Digital API running on :${port}`));
